[package]
name = "ale"
version = "0.1.0"
authors = ["Jeff Juozapaitis <Jragonmiris@gmail.com>"]

[dependencies]
libc = "0.1"
rustc-serialize = "0.3"
clippy = {version="*", optional=true}

[dev-dependencies]
rand = "0.3"

[features]
deafult = []
use_clippy = ["clippy"]